# Generated by Django 4.1.5 on 2023-02-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField()),
                ('language', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
