# Generated by Django 4.1.5 on 2023-03-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField()),
                ('language', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='app1',
        ),
    ]
